CAPSTONE (AMS)
Jessekay/AMS pull request #1
Opened 2023-03-23 08:54 UTC by Jessekay

### **THROUGH THIS MILESTONE I IMPLEMENTED THE FOLLOWING:**

- I personalized the content of my page. Choose a topic that is about African movie festivals.
- I followed all design colors
- I made the logo link to the homepage
- When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
- Featured speakers were created in javascript
- Lastly, I recorded myself describing my project.

2023-03-23 12:58 UTC, alexander16108 requested changes
Hi @Jessekay , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/UUcVHqcMwWMcUoNmSN/giphy-downsized-medium.gif"/>

## Highlights

📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 12:58 UTC, alexander16108 commented on README.md
> +
Hi, could you delete this section it is irrelevant to the details of your readme file. 😄

2023-03-23 12:58 UTC, alexander16108 commented on index.html
> +              </footer>
- in the mobile version as seen below your partner and footer sections should both be hidden and should only appear in the desktop version.

your design
![image](https://user-images.githubusercontent.com/60612329/227203767-2051cb65-6736-4248-864e-dd590401e2fe.png)
 
cindy's design
![image](https://user-images.githubusercontent.com/60612329/227203884-0020b31f-23ba-450e-99d6-cd3681455ad1.png)

- in your mobile version there is no `MORE ` button to show the full list of speakers or  `LESS` button to only see a few speakers as seen below

your version
![image](https://user-images.githubusercontent.com/60612329/227203767-2051cb65-6736-4248-864e-dd590401e2fe.png)

cindy's version
![image](https://user-images.githubusercontent.com/60612329/227204270-4f460b85-3025-47f9-98ed-9c7c853a523e.png)

2023-03-23 12:58 UTC, alexander16108 commented on about.html
> +
👋🏾  in the footer section of your about page, you ought to have both the partners section and the footer together in the mobile version but you only have the footer. please add this as it is required that your design remains identical to the template design

your design mobile version:
![image](https://user-images.githubusercontent.com/60612329/227209447-f39cf67b-4eef-4e88-a1f9-4e166cc8fbdc.png)


cindy's design
![image](https://user-images.githubusercontent.com/60612329/227209666-bf94d13d-7ff3-4b88-a920-b6ab56ea1ab6.png)

2023-03-23 12:58 UTC, alexander16108 commented on README.md
> +I would like to thank Cindy Shin in Behance for the amazing UX
it's required to give proper appreciation to Cindy for the template design with links to her profile and design 👍🏾 
*** copy the text from below and put it in the acknowledgement section of your readme file.

> I would like to give appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/)

2023-03-24 13:56 UTC, ichala approved these changes
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 16:25 UTC, merged